directory: /music/library
library: /config/beets/library.db

import:
  copy: yes
  move: no
  write: yes
  autotag: yes
  quiet: yes
  timid: no
  resume: no
  incremental: no

paths:
  default: $albumartist/$album/$track $artist - $title

plugins: []

ui:
  color: yes
