"""add_sync_history

Revision ID: c21ada10b97c
Revises: e4085c638703
Create Date: 2026-07-01 16:19:37.229672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21ada10b97c'
down_revision: Union[str, Sequence[str], None] = 'e4085c638703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracks_fetched', sa.Integer(), nullable=False),
    sa.Column('tracks_new', sa.Integer(), nullable=False),
    sa.Column('albums_updated', sa.Integer(), nullable=False),
    sa.Column('artists_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_history')
    # ### end Alembic commands ###
