"""initial

Revision ID: e4085c638703
Revises: 
Create Date: 2026-07-01 15:50:14.050820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4085c638703'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('album_mbid', sa.String(), nullable=True),
    sa.Column('qobuz_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'DOWNLOADING', 'DOWNLOADED', 'STALLED', 'REJECTED', name='album_status'), nullable=False),
    sa.Column('queue_type', sa.Enum('AUTO', 'MANUAL', 'WATCH_FOLDER', name='queue_type'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist_mbid', sa.String(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.Column('subscription_source', sa.String(), nullable=True),
    sa.Column('albums_in_library', sa.Integer(), nullable=False),
    sa.Column('total_play_count', sa.Integer(), nullable=False),
    sa.Column('last_mb_check', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('playlist_type', sa.Enum('SEASONAL', 'DISCOVER', 'OTHER', name='playlist_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('track_plays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('track_name', sa.String(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('album_name', sa.String(), nullable=False),
    sa.Column('album_mbid', sa.String(), nullable=True),
    sa.Column('artist_mbid', sa.String(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('track_name', sa.String(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('album_name', sa.String(), nullable=False),
    sa.Column('spotify_uri', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_tracks')
    op.drop_table('track_plays')
    op.drop_table('settings')
    op.drop_table('playlists')
    op.drop_table('artists')
    op.drop_table('albums')
    # ### end Alembic commands ###
