"""Default settings for Musically. Seeded when the settings table is empty on first GET request."""

DEFAULT_SETTINGS: dict[str, str] = {
    "album_play_threshold": "5",
    "artist_subscribe_play_threshold": "20",
    "library_albums_subscribe_threshold": "2",
    "sync_interval_minutes": "30",
    "new_release_check_hours": "12",
    "watch_folder_check_seconds": "60",
    "stalled_retry_intervals_hours": "[24, 72, 168, 336]",
    "backfill_days": "30",
    "max_backfill_albums": "100",
    "lastfm_enabled": "true",
    "spotify_enabled": "true",
    "qobuz_enabled": "true",
    "musicbrainz_enabled": "true",
    "watch_folder_enabled": "true",
    "spotify_seasonal_playlist_pattern": "Winter|Summer|Fall",
    "spotify_discover_playlist_names": '["Release Radar", "Pitchfork Selects"]',
    "spotify_auto_sync_playlists": "true",
    "music_library_directory": "/music/library",
    "music_downloads_watch_directory": "/music/downloads",
    "qobuz_temp_download_directory": "/downloads",
    "beets_config_path": "/config/beets/config.yaml",
    "beets_path_format": "$albumartist/$album/$disc-$track $artist - $title",
    "beets_import_quiet": "true",
    "beets_import_copy": "false",
    "beets_import_write": "true",
    "beets_import_autotag": "true",
    "discord_webhook_url": "",
    "notify_on_download": "true",
    "notify_on_queued_manual": "true",
    "notify_on_stalled": "true",
    "notify_on_error": "true",
    "notify_on_watch_folder": "true",
    "lastfm_api_key": "",
    "lastfm_username": "",
    "spotify_client_id": "",
    "spotify_client_secret": "",
    "spotify_redirect_uri": "http://localhost:8000/api/spotify/auth/callback",
    "qobuz_email": "",
    "qobuz_password_encrypted": "",
    "lastfm_rate_limit_rps": "4.5",
    "spotify_rate_limit_rpm": "150",
    "musicbrainz_rate_limit_rps": "0.9",
    "qobuz_rate_limit_rps": "2.0",
}

SETTING_CATEGORIES: dict[str, str] = {
    "album_play_threshold": "thresholds",
    "artist_subscribe_play_threshold": "thresholds",
    "library_albums_subscribe_threshold": "thresholds",
    "sync_interval_minutes": "scheduling",
    "new_release_check_hours": "scheduling",
    "watch_folder_check_seconds": "scheduling",
    "stalled_retry_intervals_hours": "scheduling",
    "backfill_days": "scheduling",
    "max_backfill_albums": "scheduling",
    "lastfm_enabled": "sources",
    "spotify_enabled": "sources",
    "qobuz_enabled": "sources",
    "musicbrainz_enabled": "sources",
    "watch_folder_enabled": "sources",
    "spotify_seasonal_playlist_pattern": "sources",
    "spotify_discover_playlist_names": "sources",
    "spotify_auto_sync_playlists": "sources",
    "music_library_directory": "library_paths",
    "music_downloads_watch_directory": "library_paths",
    "qobuz_temp_download_directory": "library_paths",
    "beets_config_path": "beets",
    "beets_path_format": "beets",
    "beets_import_quiet": "beets",
    "beets_import_copy": "beets",
    "beets_import_write": "beets",
    "beets_import_autotag": "beets",
    "discord_webhook_url": "notifications",
    "notify_on_download": "notifications",
    "notify_on_queued_manual": "notifications",
    "notify_on_stalled": "notifications",
    "notify_on_error": "notifications",
    "notify_on_watch_folder": "notifications",
    "lastfm_api_key": "api_keys",
    "lastfm_username": "api_keys",
    "spotify_client_id": "api_keys",
    "spotify_client_secret": "api_keys",
    "spotify_redirect_uri": "api_keys",
    "spotify_access_token_encrypted": "api_keys",
    "spotify_refresh_token": "api_keys",
    "spotify_token_expiry": "api_keys",
    "spotify_pkce_verifier": "api_keys",
    "spotify_pkce_state": "api_keys",
    "qobuz_email": "api_keys",
    "qobuz_password_encrypted": "api_keys",
    "lastfm_rate_limit_rps": "rate_limiting",
    "spotify_rate_limit_rpm": "rate_limiting",
    "musicbrainz_rate_limit_rps": "rate_limiting",
    "qobuz_rate_limit_rps": "rate_limiting",
}
