"""Default settings for Musically. Seeded when the settings table is empty on first GET request."""

DEFAULT_SETTINGS: dict[str, str] = {
    "album_play_threshold": "5",
    "artist_subscribe_play_threshold": "20",
    "library_albums_subscribe_threshold": "2",
    "swipe_min_track_count": "4",
    "max_concurrent_downloads": "3",
    "sync_interval_minutes": "30",
    "new_release_check_hours": "12",
    "watch_folder_check_seconds": "60",
    "stalled_retry_intervals_hours": "[24, 72, 168, 336]",
    "backfill_days": "30",
    "max_backfill_albums": "100",
    "lastfm_enabled": "true",
    "spotify_enabled": "true",
    "qobuz_enabled": "true",
    "musicbrainz_enabled": "true",
    "watch_folder_enabled": "true",
    "spotify_seasonal_playlist_pattern": "Winter|Summer|Fall",
    "spotify_discover_playlist_names": '["Release Radar", "Pitchfork Selects"]',
    "spotify_auto_sync_playlists": "true",
    "music_library_directory": "/music/library",
    "music_downloads_watch_directory": "/music/downloads",
    "qobuz_temp_download_directory": "/downloads",
    "beets_config_path": "/config/beets/config.yaml",
    "beets_path_format": "$albumartist/$album/$disc-$track $artist - $title",
    "beets_import_quiet": "true",
    "beets_import_copy": "false",
    "beets_import_write": "true",
    "beets_import_autotag": "true",
    "discord_webhook_url": "",
    "notify_on_download": "true",
    "notify_on_queued_manual": "true",
    "notify_on_stalled": "true",
    "notify_on_error": "true",
    "notify_on_watch_folder": "true",
    "lastfm_api_key": "",
    "lastfm_username": "",
    "spotify_client_id": "",
    "spotify_client_secret": "",
    "spotify_redirect_uri": "http://localhost:8000/api/spotify/auth/callback",
    "qobuz_email": "",
    "qobuz_password_encrypted": "",
    "lastfm_rate_limit_rps": "4.5",
    "spotify_rate_limit_rpm": "150",
    "musicbrainz_rate_limit_rps": "0.9",
    "qobuz_rate_limit_rps": "2.0",
}

SETTING_DESCRIPTIONS: dict[str, str] = {
    "album_play_threshold": "Minimum total plays before an album is auto-queued for download.",
    "artist_subscribe_play_threshold": "Minimum total plays across all albums before auto-subscribing to an artist.",
    "library_albums_subscribe_threshold": "Minimum albums already in library before auto-subscribing to an artist.",
    "swipe_min_track_count": "Albums with fewer tracks than this are never queued for swipe review (e.g. singles with only 1–2 tracks).",
    "max_concurrent_downloads": "Maximum number of albums to download simultaneously. Approved albums queue up when all slots are busy.",
    "sync_interval_minutes": "How often the rule engine and sync tasks run (in minutes).",
    "new_release_check_hours": "How often to check subscribed artists for new releases (in hours).",
    "watch_folder_check_seconds": "How often to scan the watch folder for new downloads (in seconds).",
    "stalled_retry_intervals_hours": "JSON array of retry intervals for stalled downloads (in hours).",
    "backfill_days": "Number of past days to backfill track plays from LastFM on first sync.",
    "max_backfill_albums": "Maximum number of albums to backfill during initial LastFM sync.",
    "lastfm_enabled": "Enable LastFM as a data source for track plays and recommendations.",
    "spotify_enabled": "Enable Spotify playlist integration.",
    "qobuz_enabled": "Enable Qobuz as a download source.",
    "musicbrainz_enabled": "Enable MusicBrainz metadata lookups.",
    "watch_folder_enabled": "Enable automatic import of albums dropped into the watch folder.",
    "spotify_seasonal_playlist_pattern": "Regex pattern to match seasonal playlists (e.g. Winter, Summer).",
    "spotify_discover_playlist_names": 'JSON array of playlist names to treat as "discover" sources.',
    "spotify_auto_sync_playlists": "Automatically sync Spotify playlists on schedule.",
    "music_library_directory": "Root directory of your organized music library.",
    "music_downloads_watch_directory": "Directory watched for new downloads to auto-import.",
    "qobuz_temp_download_directory": "Temporary directory for Qobuz downloads before import.",
    "beets_config_path": "Path to the beets config.yaml file.",
    "beets_path_format": "File naming format used by beets for imported tracks.",
    "beets_import_quiet": "Run beets import in quiet mode (less output).",
    "beets_import_copy": "Copy files into the library (instead of moving).",
    "beets_import_write": "Write metadata tags to imported files.",
    "beets_import_autotag": "Automatically tag files using MusicBrainz during import.",
    "discord_webhook_url": "Discord webhook URL for notifications.",
    "notify_on_download": "Send Discord notification when an album download completes.",
    "notify_on_queued_manual": "Send Discord notification when an album is manually queued.",
    "notify_on_stalled": "Send Discord notification when a download stalls.",
    "notify_on_error": "Send Discord notification on errors.",
    "notify_on_watch_folder": "Send Discord notification when a watch folder import starts.",
    "lastfm_api_key": "Your LastFM API key.",
    "lastfm_username": "Your LastFM username for scrobbling history.",
    "spotify_client_id": "Spotify app client ID for OAuth.",
    "spotify_client_secret": "Spotify app client secret for OAuth.",
    "spotify_redirect_uri": "OAuth redirect URI for Spotify authentication.",
    "qobuz_email": "Qobuz account email for downloads.",
    "qobuz_password_encrypted": "Qobuz account password (encrypted at rest).",
    "lastfm_rate_limit_rps": "Maximum requests per second to LastFM API.",
    "spotify_rate_limit_rpm": "Maximum requests per minute to Spotify API.",
    "musicbrainz_rate_limit_rps": "Maximum requests per second to MusicBrainz API.",
    "qobuz_rate_limit_rps": "Maximum requests per second to Qobuz API.",
}

SETTING_CATEGORIES: dict[str, str] = {
    "album_play_threshold": "thresholds",
    "artist_subscribe_play_threshold": "thresholds",
    "library_albums_subscribe_threshold": "thresholds",
    "swipe_min_track_count": "thresholds",
    "max_concurrent_downloads": "thresholds",
    "sync_interval_minutes": "scheduling",
    "new_release_check_hours": "scheduling",
    "watch_folder_check_seconds": "scheduling",
    "stalled_retry_intervals_hours": "scheduling",
    "backfill_days": "scheduling",
    "max_backfill_albums": "scheduling",
    "lastfm_enabled": "sources",
    "spotify_enabled": "sources",
    "qobuz_enabled": "sources",
    "musicbrainz_enabled": "sources",
    "watch_folder_enabled": "sources",
    "spotify_seasonal_playlist_pattern": "sources",
    "spotify_discover_playlist_names": "sources",
    "spotify_auto_sync_playlists": "sources",
    "music_library_directory": "library_paths",
    "music_downloads_watch_directory": "library_paths",
    "qobuz_temp_download_directory": "library_paths",
    "beets_config_path": "beets",
    "beets_path_format": "beets",
    "beets_import_quiet": "beets",
    "beets_import_copy": "beets",
    "beets_import_write": "beets",
    "beets_import_autotag": "beets",
    "discord_webhook_url": "notifications",
    "notify_on_download": "notifications",
    "notify_on_queued_manual": "notifications",
    "notify_on_stalled": "notifications",
    "notify_on_error": "notifications",
    "notify_on_watch_folder": "notifications",
    "lastfm_api_key": "api_keys",
    "lastfm_username": "api_keys",
    "spotify_client_id": "api_keys",
    "spotify_client_secret": "api_keys",
    "spotify_redirect_uri": "api_keys",
    "spotify_access_token_encrypted": "api_keys",
    "spotify_refresh_token": "api_keys",
    "spotify_token_expiry": "api_keys",
    "spotify_pkce_verifier": "api_keys",
    "spotify_pkce_state": "api_keys",
    "qobuz_email": "api_keys",
    "qobuz_password_encrypted": "api_keys",
    "lastfm_rate_limit_rps": "rate_limiting",
    "spotify_rate_limit_rpm": "rate_limiting",
    "musicbrainz_rate_limit_rps": "rate_limiting",
    "qobuz_rate_limit_rps": "rate_limiting",
}
